-- Cairn walking skeleton — the signed event envelope (Spike 0001 §3, §4).
--
-- This is the *day-one, can't-retrofit* shape: every column here is reserved
-- because an append-only log cannot grow these later without rewriting history
-- (the same reason t_effective and the encryption-capable body slot are day-one
-- in data-model §3.5/§3.6/§3.8). The walking skeleton exists to exercise this
-- shape on real hardware over a real link before it is frozen into an ADR.
--
-- Relationship to poc/replication-failover: that PoC proved set-union
-- convergence with a *bare* event_log (no signatures, projections-as-views).
-- This skeleton wraps the signed COSE_Sign1 envelope around the same HLC-ordered
-- log, adds an in-database content-address invariant, a trigger-maintained
-- projection (002), and a BLAKE3 content-addressed blob tier (003).
--
-- Target: PostgreSQL >= 18 (uuidv7(), the project floor). Loaded identically
-- into every node; a node's identity is just the string it stamps on origin.

BEGIN;

-- Content-addressing and the legibility twin lean on pgcrypto's digest().
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Maximum size of one signed event, enforced at EVERY admission door (submit_event,
-- submit_node_event, apply_remote_node_event, restore_node_event). This is the WRITE-side
-- counterpart of the wire/backup read caps (sync.rs MAX_FRAME_BYTES / medium.rs
-- MAX_CHUNK_BYTES, both 8 MiB): those caps REFUSE an oversized event on read, and because
-- a puller aborts mid-stream without checkpointing, a single oversized-but-admitted event
-- would wedge sync at that seq forever AND could clobber a good backup medium. Refusing
-- oversize at admission makes that unreachable — the read caps become true dead paths for
-- honest data. Set below the 8 MiB (8,388,608-byte) frame cap with headroom for framing.
-- (Review finding A7a. Attachments are content-addressed blobs on the byte tier, NOT
-- inlined here, so a legitimate clinical event never approaches this bound — ADR-0013.)
CREATE OR REPLACE FUNCTION cairn_max_event_bytes()
RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT 8000000 $$;

-- ---------------------------------------------------------------------------
-- The append-only, signed clinical event log (governing principle #1).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS event_log (
    -- Identity & causal order ------------------------------------------------
    event_id        UUID    PRIMARY KEY,        -- UUIDv7, generated by the signer; INSIDE the signed bytes
    patient_id      UUID    NOT NULL,           -- the immortal subject UUID this event is about
    event_type      TEXT    NOT NULL,           -- 'patient.created' | 'patient.amended' | 'note.added' | ...
    schema_version  TEXT    NOT NULL,           -- §3.13 join key; additive-only evolution

    -- Bitemporal time (§3.6): t_recorded is the HLC ceiling; t_effective is the
    -- freely-backdatable *claim* (NULL = not asserted / unknown — principle 4).
    hlc_wall        BIGINT  NOT NULL,           -- t_recorded: physical component (ms)
    hlc_counter     INTEGER NOT NULL,           -- t_recorded: logical tiebreak
    node_origin     TEXT    NOT NULL,           -- which node FIRST recorded (third sort key)
    t_effective     TIMESTAMPTZ,                -- asserted effective time; NULL-able on purpose

    -- The signed artifact (§4, structural move 1) ----------------------------
    -- signed_bytes IS the event: a COSE_Sign1 (RFC 9052) wire blob whose payload
    -- is the canonical-CBOR body. It is stored verbatim and NEVER re-serialized;
    -- everything below is a *derived view* of it, for indexing and projection.
    signed_bytes    BYTEA   NOT NULL,
    -- Self-describing content address (§4 move 2): multihash(sha2-256) of the
    -- signed bytes. The hash IS the event's identity, exactly as in §3.14.
    content_address BYTEA   NOT NULL UNIQUE,

    -- Derived view of the signed body (JSONB) — parsed FROM signed_bytes by the
    -- applying node, never authoritative, never round-tripped back to bytes.
    body            JSONB   NOT NULL,
    -- §3.9 contributor set (skeleton: a single author is enough). signer_key_id
    -- selects the verifying key; verification happens on apply (Bet A2), and in
    -- production moves in-DB via the ADR-0002 pgrx hatch (see note below).
    contributors    JSONB   NOT NULL,
    signer_key_id   TEXT    NOT NULL,

    -- §3.13 mandatory plaintext legibility twin (also the FTS/RAG substrate).
    plaintext_twin  TEXT    NOT NULL,

    -- Encryption-capable body slot (§3.8 / ADR-0005), stubbed off in the
    -- skeleton: sealed=false, dek_wrapped=NULL. Reserved day-one so crypto-shred
    -- can be added without an envelope change.
    sealed          BOOLEAN NOT NULL DEFAULT FALSE,
    dek_wrapped     BYTEA,

    -- §3.14 attachment references: an array of {alg, digest, media_type,
    -- descriptor}. The reference is eager (here); the BYTES are lazy (003).
    attachments     JSONB   NOT NULL DEFAULT '[]'::jsonb,

    recorded_at     TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),  -- local arrival

    -- Content-address invariant, enforced in the database (§4 move 1 + §3.14):
    -- a row whose advertised address does not match its bytes is refused at the
    -- boundary. multihash prefix 0x12 0x20 = sha2-256, 32 bytes.
    CONSTRAINT event_content_addressed
        CHECK (content_address = '\x1220'::bytea || digest(signed_bytes, 'sha256')),
    -- t_recorded is a ceiling: the asserted effective time may precede it
    -- (backdating is legal) but the log never claims to have recorded the
    -- future. Clashes are flagged elsewhere, never auto-resolved (§3.6).
    CONSTRAINT hlc_nonnegative CHECK (hlc_wall >= 0 AND hlc_counter >= 0)
);

CREATE INDEX IF NOT EXISTS event_log_order_idx
    ON event_log (hlc_wall, hlc_counter, node_origin);
CREATE INDEX IF NOT EXISTS event_log_patient_idx
    ON event_log (patient_id);

-- NOTE (safety-critical seam, §9 / ADR-0002): Ed25519 signature verification is
-- the one check this skeleton performs in the Rust apply path (cairn-sync), not
-- in SQL, because core PostgreSQL cannot verify EdDSA. In production this gate
-- moves into an in-database pgrx function so it is *unbypassable* — no row
-- enters event_log unless its COSE_Sign1 verifies against a registered key.
-- The content-address CHECK above is the part that IS expressible in core SQL.

-- Append-only enforcement (principle #1): refuse UPDATE and DELETE outright.
CREATE OR REPLACE FUNCTION event_log_is_append_only()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'event_log is append-only: % is not permitted (Cairn principle #1)', TG_OP;
END;
$$;

DROP TRIGGER IF EXISTS event_log_no_update ON event_log;
CREATE TRIGGER event_log_no_update BEFORE UPDATE OR DELETE ON event_log
    FOR EACH ROW EXECUTE FUNCTION event_log_is_append_only();

-- ---------------------------------------------------------------------------
-- Per-node Hybrid Logical Clock (single row). Advanced on every local write
-- and merged forward on every applied remote event (§3.6, ADR-0003).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS hlc_state (
    id          BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (id),
    hlc_wall    BIGINT  NOT NULL DEFAULT 0,
    hlc_counter INTEGER NOT NULL DEFAULT 0
);
INSERT INTO hlc_state (id, hlc_wall, hlc_counter)
    VALUES (TRUE, 0, 0) ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Sync watermark per peer: the highest HLC this node has pulled from a peer.
-- Pull is a resumable set-union; the watermark is a hint, never an authority
-- (ADR-0004) — re-pulling from 0 must converge to the identical set.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sync_state (
    peer         TEXT    PRIMARY KEY,
    hlc_wall     BIGINT  NOT NULL DEFAULT 0,
    hlc_counter  INTEGER NOT NULL DEFAULT 0,
    last_pull_at TIMESTAMPTZ
);

COMMIT;
